passed first testcase
scarletstudio/butterfly pull request #262
Opened 2022-07-12 02:26 UTC by BoominHutJr

Finished basic implementation, working on test cases.

2022-07-15 00:19 UTC, erikqu requested changes

2022-07-15 00:19 UTC, erikqu commented on pipeline/matching/generators/rare_interests.py
> +# used to count occurences in a list
Remove misc. comments unless clever logic (applies everywhere)

2022-07-15 00:19 UTC, erikqu commented on pipeline/matching/generators/rare_interests.py
> +        usrList = inp.users
feel free to rename the input var name in this method

2022-07-15 00:19 UTC, erikqu commented on pipeline/matching/generators/rare_interests.py
> +        m = []
Lets name this something meaningful

2022-07-15 00:19 UTC, erikqu commented on pipeline/matching/generators/rare_interests.py
> +                    score=round(rarityScore, 2),
Nice, rounding this was a good idea

2022-07-17 17:06 UTC, BoominHutJr commented
- added tests to cover cases  in which there are 1 rare interest, multiple rare interests, and all interests are equally rare
- fixed null input check
- fixed rare interest list reflecting rare interests of the community rather than individual matches

2022-07-17 17:11 UTC, BoominHutJr commented
- added test for scenario of a community that has no common interests

2022-07-19 01:59 UTC, erikqu commented on pipeline/matching/generators/rare_interests_test.py
> +        interests=[hiking, swimming, reading],
Should we have cooking here?

2022-07-19 02:04 UTC, BoominHutJr commented on pipeline/matching/generators/rare_interests_test.py
> +        interests=[hiking, swimming, reading],
yes, thanks for catching that

2022-07-22 21:47 UTC, bridgettorres commented
LGTM!

2022-07-25 01:10 UTC, bridgettorres commented on pipeline/matching/generators/rare_interests.py
> +        yield from resultingMatch
Everything looks clean and easy to read, LGTM!

2022-07-25 01:11 UTC, bridgettorres commented on pipeline/matching/generators/rare_interests_test.py
> +    assert actual == expected
Good test cases, clear names!

2022-07-26 01:21 UTC, erikqu commented on pipeline/matching/generators/rare_interests.py
> +        # convert to set and back to list to remove duplicates
Lets remove this comment

2022-07-26 01:24 UTC, erikqu commented on pipeline/matching/generators/rare_interests.py
> +                    rarityScoreDict.items(), key=lambda x: x[1]
This could be perceived as clever, maybe a comment here would be nice

2022-07-26 01:53 UTC, erikqu approved these changes

2022-07-26 02:06 UTC, merged