Luis new branch
scarletstudio/butterfly pull request #381
Opened 2022-08-05 22:38 UTC by lacosta2

added icons that change depending on who sent the last message in chatpreview

2022-08-05 22:39 UTC, lacosta2 commented
test

2022-08-06 01:29 UTC, vingkan requested changes
Awesome work @lacosta2! This looks really good. I love the icons you guys picked.

Here are some screenshots I took:
<div>
<img style="display: inline-block;" width="250" alt="Screen Shot 2022-08-05 at 8 20 41 PM" src="https://user-images.githubusercontent.com/11896652/183228227-d934f736-95e1-4b62-a9b3-ca1dbaf70f6d.png">
<img style="display: inline-block;" width="250" alt="Screen Shot 2022-08-05 at 8 21 04 PM" src="https://user-images.githubusercontent.com/11896652/183228228-a9d47372-b1fa-4a36-b1df-162a2840c3cd.png">
</div>

2022-08-06 01:29 UTC, vingkan commented on frontend/src/app/inbox/ChatInbox.tsx
> +            return <ChatPreview key={c.id} match={c} users={users} community={com} chatData={c} />
There is already a property for this, though it is called `match`. If you look in the property list, they both have the value `c`.

2022-08-06 01:29 UTC, vingkan commented on frontend/src/app/inbox/ChatPreview.tsx
> +    const currentChat: ChatData = chatData
This is just a variable rename, if you want to show the type of the arguments you can do this:

```tsx
interface ChatPreviewProps {
  match: ChatData
  users: { [userId: string]: UserData }
  community: CommunityData
}

export default function ChatPreview({ match, users, community, chatData }: ChatPreviewProps) { ... }
```

2022-08-06 01:29 UTC, vingkan commented on frontend/src/app/inbox/ChatPreview.tsx
> +                    </div>
You can it easier to read the JSX/HTML by saving the icon you want to a variable and then injecting it. Like this:

```tsx
// Save each icon as a variable
const iconResponded = <FontAwesomeIcon icon={faCircleCheck} className="readIcon" />
const iconNotResponded = <FontAwesomeIcon icon={faMoon} className="readIcon" />
// Save a variable for the condition
const hasResponded = authUser?.uid === currentChat.latestMessage?.from

// Save the chosen icon based on the condition to a variable
const iconRespondedStatus = hasResponded ? iconResponded : iconNotResponded

// Insert the chosen icon into the layout
return (
  ...
  <div>{iconRespondedStatus}</div>
  ...
)
```

2022-08-21 00:26 UTC, vingkan approved these changes

2022-08-21 00:27 UTC, merged